---
- name: create IBM CLOUD S3 secrets
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: ibm-s3-bucket-secrets-backup
        namespace: "{{ ansible_operator_meta.namespace }}"
        labels:
          app: node-red-app
      type: Opaque
      stringData:
        API_KEY: "{{ ibm_s_3.api_key }}"
        BUCKET_NAME: "{{ ibm_s_3.bucket_name }}"
        ENDPOINT: "{{ ibm_s_3.endpoint }}"
        AUTH_ENDPOINT: "{{ ibm_s_3.auth_endpoint }}"
        RESOURCE_CRN: "{{ ibm_s_3.resource_crn}}"
